# 词袋法&TFIDF

In [6]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer,TfidfTransformer

In [7]:
arr1 = [
    "This is spark, spark sql a every good",
    "Spark Hadoop Hbase",
    "This is sample",
    "This is anthor example anthor example",
    "spark hbase hadoop spark hive hbase hue oozie",
    "hue oozie spark"
]
arr2 = [
    "this is a sample a example",
    "this cd is another another sample example example",
    "spark Hbase hadoop Spark hive hbase"
]


In [8]:
# 相当于词袋法
count = CountVectorizer(min_df=0.1, dtype=np.float64, ngram_range=(0,1))
df1 = count.fit_transform(arr1)
print(df1)
print (df1.toarray())
print (count.get_stop_words())
print (count.get_feature_names_out())
print ("转换另外的文档数据")
print (count.transform(arr2).toarray())


  (0, 13)	1.0
  (0, 8)	1.0
  (0, 11)	2.0
  (0, 12)	1.0
  (0, 1)	1.0
  (0, 3)	1.0
  (1, 11)	1.0
  (1, 4)	1.0
  (1, 5)	1.0
  (2, 13)	1.0
  (2, 8)	1.0
  (2, 10)	1.0
  (3, 13)	1.0
  (3, 8)	1.0
  (3, 0)	2.0
  (3, 2)	2.0
  (4, 11)	2.0
  (4, 4)	1.0
  (4, 5)	2.0
  (4, 6)	1.0
  (4, 7)	1.0
  (4, 9)	1.0
  (5, 11)	1.0
  (5, 7)	1.0
  (5, 9)	1.0
[[0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 2. 1. 1.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1.]
 [2. 0. 2. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 2. 1. 1. 0. 1. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0.]]
None
['anthor' 'every' 'example' 'good' 'hadoop' 'hbase' 'hive' 'hue' 'is'
 'oozie' 'sample' 'spark' 'sql' 'this']
转换另外的文档数据
[[0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 2. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 2. 1. 0. 0. 0. 0. 2. 0. 0.]]


In [9]:
# 基于TF的值(词袋法)，做一个IDF的转换
tfidf_t = TfidfTransformer()
df2 = tfidf_t.fit_transform(df1)
print (df2.toarray())
print ("转换另外的文档数据")
print (tfidf_t.transform(count.transform(arr2)).toarray())

[[0.         0.43167582 0.         0.43167582 0.         0.
  0.         0.         0.29885453 0.         0.         0.51219126
  0.43167582 0.29885453]
 [0.         0.         0.         0.         0.62951441 0.62951441
  0.         0.         0.         0.         0.         0.4554374
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.49468646 0.         0.71454223 0.
  0.         0.49468646]
 [0.66820557 0.         0.66820557 0.         0.         0.
  0.         0.         0.23130351 0.         0.         0.
  0.         0.23130351]
 [0.         0.         0.         0.         0.30742585 0.61485171
  0.37490304 0.30742585 0.         0.30742585 0.         0.44482931
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.62951441 0.         0.62951441 0.         0.4554374
  0.         0.        ]]
转换另外的文档数据
[[0.         0.         0.58137639 0.         0.         0.
  0.         

In [10]:
## 相当TF+IDF(先做词袋法再做IDF转换)
tfidf_v = TfidfVectorizer(min_df=0, dtype=np.float64)
df3 = tfidf_v.fit_transform(arr1)
print (df3.toarray())
print (tfidf_v.get_feature_names())
print (tfidf_v.get_stop_words())
print ("转换另外的文档数据")
print (tfidf_v.transform(arr2).toarray())

[[0.         0.43167582 0.         0.43167582 0.         0.
  0.         0.         0.29885453 0.         0.         0.51219126
  0.43167582 0.29885453]
 [0.         0.         0.         0.         0.62951441 0.62951441
  0.         0.         0.         0.         0.         0.4554374
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.49468646 0.         0.71454223 0.
  0.         0.49468646]
 [0.66820557 0.         0.66820557 0.         0.         0.
  0.         0.         0.23130351 0.         0.         0.
  0.         0.23130351]
 [0.         0.         0.         0.         0.30742585 0.61485171
  0.37490304 0.30742585 0.         0.30742585 0.         0.44482931
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.62951441 0.         0.62951441 0.         0.4554374
  0.         0.        ]]
['anthor', 'every', 'example', 'good', 'hadoop', 'hbase', 'hive', 'hue', 'is', 'ooz

C:\Users\lq\.conda\envs\py37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
