In [3]:
# 画图弹窗
%matplotlib tk
# 画图inline
# %matplotlib inline

In [5]:
flag = True
if flag:
    # 添加一个截距项对应的X值
    X = np.column_stack((X1, np.ones(shape=(X1.shape[0], 1))))
    # X = np.hstack((X1,np.ones(shape=(X1.shape[0], 1))))
else:
    # 不加入截距项
    X = X1
print(X)
# print(Y)

[[10.  1.  1.]
 [15.  1.  1.]
 [20.  1.  1.]
 [30.  1.  1.]
 [50.  2.  1.]
 [60.  1.  1.]
 [60.  2.  1.]
 [70.  2.  1.]]


In [7]:
# 三、根据解析式的公式求解theta的值
theta = (X.T * X).I * X.T * Y
print(theta)

[[0.03921348]
 [0.25262172]
 [0.40861423]]


In [9]:
# 基于训练好的模型参数对一个未知的样本做一个预测
if flag:
    x = np.mat(np.array([[55.0, 2.0,1.0]]))
else:
    x = np.mat(np.array([[55.0, 2.0]]))
pred_y = x * theta
print("当面积为55平并且房间数目为2的时候，预测价格为:{}".format(pred_y))

当面积为55平并且房间数目为2的时候，预测价格为:[[3.07059925]]
